apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: das
  name: test-http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-http
  namespace: test-http
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-http
  namespace: test-http
  labels:
    app.kubernetes.io/name: test-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: test-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-http
    spec:
      serviceAccountName: test-http
      containers:
      - name: test-http
        image: strm/helloworld-http
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
